### ISSUE TITLE
Support for Gitlab project sub-folders

### ISSUE THREAD

**Issue by Aldekein** [assistify/rcapps-gitlab#14]
Out Gitlab URL for the project is https://gitlab.xxxxx.xxxx/landings/orderbook/spacex/
I created a room in Rocket.chat with name landings-orderbook-spacex

But on testing there's an error:
`Hook executed successfully but returned HTTP 500 Room landings-orderbook/spacex not found`

It's not possible to create a room with slash in the name so the integration is not possible :(

**Comment by jschirrmacher** [comment]
It might work if you replace the slashed with dashes.

**Comment by Aldekein** [comment]
Where can I replace it?

**Comment by jschirrmacher** [comment]
The room name should use dashes instead of slashes.

**Comment by jschirrmacher** [comment]
I fact, I didn't understand you right, at first. You already _did_ name the room using dashes instead of slashes. However, it was an error in a previous version, [which I already fixed](https://github.com/assistify/rcapps-gitlab/commit/65ef52ad8340e8c5f9b9103ad3c6d6c4f71b015e), that only the first slash in the repository path was changed to a dash, so that subfolders didn't work.

So, I assume that you use an old version of the app. Could you please check or install the most current version?

**Comment by Aldekein** [comment]
I installed it for a first time 5 days ago from Marketplace tab, so it should have fix from 2019 year. Is the offered version actual?

![image](https://user-images.githubusercontent.com/671454/78009446-b550ce00-7349-11ea-9d88-61e6eeb5568e.png)

**Comment by jschirrmacher** [comment]
No, it doesn't seem to be. I've triggered a new deployment of a 0.1.0 version now, so as soon as Rocket.Chat decides to publish, it should be available in the Marketplace.

**Comment by guglez** [comment]
Same issue here. Did rocket chat release the new version of your app?

**Comment by jschirrmacher** [comment]
Not yet, but I'm in contact.
You would see in your list of installed apps, if so. Regrettably, it is not visible in the marketplace itself.

**Comment by jschirrmacher** [comment]
Good news, the new version is approved now!
